### ISSUE TITLE
Images Flicker Onscreen

### ISSUE THREAD

**Issue by muletmiles** [OOP-Team-Project/RPG-Interation-1#50]
Not sure if this is just my terrible laptop not being able to draw things fast enough, but Entities, Items, and Decals flicker on and off constantly (and especially when moving) on the screen.

[Note: The colors are off in the gif, but this is the flickering that I'm seeing]
![issuething](https://cloud.githubusercontent.com/assets/13969902/12871130/e41c9708-cd37-11e5-89ec-899421701feb.gif)

**Comment by JoshNassar94** [comment]
Is that really what everything looks like on your machine??
All that aside...mine flickers a tiny bit...but usually only when I run through a decal with the avatar

**Comment by muletmiles** [comment]
Maybe it's time to get a new computer...
